var hotels = [
    {
        'id': 1,
        'name': 'Light bright airy stylish apt and safe peaceful way Coxs Bazar' ,
        'image': 'Rectangle 26',
        'guest': '4 guest ',
        'room': '2 bedrooms ',
        'bed': '2 bed ',
        'bath': '2 bath ',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 34,

    },
    {
        'id': 1,
        'name': 'Apparment in lost panoroma  Coxs Bazar' ,
        'image': 'Rectangle 27',
        'guest': '3 guest',
        'room': '2 bedrooms',
        'bed': '2 bed',
        'bath': '2 bath',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 35,

    },
    {
        'id': 1,
        'name': 'AR lounge & pool  Coxs Bazar' ,
        'image': 'Rectangle 28',
        'guest': '2 guest',
        'room': '2 bedrooms',
        'bed': '2 bed',
        'bath': '2 bath',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 36,

    },
    {
        'id': 2,
        'name': 'Light bright airy stylish apt and safe peaceful way Sremangal' ,
        'image': 'Rectangle 26',
        'guest': '4 guest ',
        'room': '2 bedrooms ',
        'bed': '2 bed ',
        'bath': '2 bath ',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 34,

    },
    {
        'id': 2,
        'name': 'Apparment in lost panoroma Sremangal' ,
        'image': 'Rectangle 27',
        'guest': '3 guest',
        'room': '2 bedrooms',
        'bed': '2 bed',
        'bath': '2 bath',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 35,

    },
    {
        'id': 2,
        'name': 'AR lounge & pool Sremangal ' ,
        'image': 'Rectangle 28',
        'guest': '2 guest',
        'room': '2 bedrooms',
        'bed': '2 bed',
        'bath': '2 bath',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 36,

    },
    {
        'id': 3,
        'name': 'Light bright airy stylish apt and safe peaceful way Sundarbans' ,
        'image': 'Rectangle 26',
        'guest': '4 guest ',
        'room': '2 bedrooms ',
        'bed': '2 bed ',
        'bath': '2 bath ',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 34,

    },
    {
        'id': 3,
        'name': 'Apparment in lost panoroma Sundarbans' ,
        'image': 'Rectangle 27',
        'guest': '3 guest',
        'room': '2 bedrooms',
        'bed': '2 bed',
        'bath': '2 bath',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 35,

    },
    {
        'id': 3,
        'name': 'AR lounge & pool Sundarbans ' ,
        'image': 'Rectangle 28',
        'guest': '2 guest',
        'room': '2 bedrooms',
        'bed': '2 bed',
        'bath': '2 bath',
        'ac': 'Air conditioning kitchen availble',
        'cancel' : 'Cancelation facility availble',
        'rating' : 4.6,
        'rating_count': 20,
        'price_per_night': 36,

    },



];
export default hotels;
